Add rjust to force 4 digit crc-16
pedrofurtado/qrcode_pix_ruby pull request #27
Opened 2022-09-14 20:39 UTC by everestcw

We've noticed that in some cases when the Hex value of the CRC-16 starts with a 0 the conversion to string removes the zeros on the start. With this, we fix this problem. I've also added a taste to simulate that scenario.

2022-09-16 00:40 UTC, pedrofurtado commented
Fala Caio, @everestcw , tudo joia? 👋 

Obrigado pela contribuição 🎉 

Está tudo certinho, irei mesclar e gerar uma nova release!

2022-09-16 00:41 UTC, pedrofurtado approved these changes

2022-09-16 01:16 UTC, pedrofurtado requested changes
@everestcw Caio, poderia por gentileza atualizar sua branch com a master e gerar uma entrada em CHANGELOG.md? Apos isso, acredito que o CI fique ok ✅

2022-09-17 19:53 UTC, everestcw commented
> @everestcw Caio, poderia por gentileza atualizar sua branch com a master e gerar uma entrada em CHANGELOG.md? Apos isso, acredito que o CI fique ok ✅

Fala, Pedro. Fiz os ajustes que você pediu. 👍

2022-09-19 22:44 UTC, pedrofurtado commented
@everestcw o CI falhou, provável q a alteração tenha quebrado algo no comportamento. Vale dar uma zoiadinha belê, rodar a suíte localmente qq coisa 🤝

2023-02-28 11:41 UTC, closed without merging